-- Seed file for Amharic Proverbs Database
-- Populates the proverbs table with the initial 16 proverbs.

INSERT INTO public.proverbs (slug, amharic_text, english_translation, meaning_amharic, meaning_english) VALUES
('one-cannot-fish-by-scooping-water', 'ውሃ ጠልፎ ዐሣ አይጠመዱ', 'One cannot fish by scooping water.', 'ዐሣ ለማጥመድ ትዕግስትና ትክክለኛ ዘዴ ያስፈልጋል። ትልቅ ነገር ለማሳካት መቸኮልና ዘዴ ማጣት አይረዳም።', 'Great results require patience and the right method. Rushing and working without strategy will lead to failure, no matter how hard one tries.'),
('one-hand-cannot-clap', 'አንድ እጅ ጮክ አይልም', 'One hand cannot clap.', 'ብቻዬን ምንም ማድረግ አይቻልም። ትብብርና አንድነት ሳይኖር ትልቅ ሥራ አይሳካም።', 'Cooperation is essential. No significant achievement can happen alone — unity and collaboration are the foundation of success.'),
('a-foolish-supporter-will-destroy', 'ሞኝ ደጋፊ ያፈርሳል', 'A foolish supporter will destroy.', 'ምንም ያህል ሊረዳ ቢፈልግ፣ የሞኝ እርዳታ ጥፋት ያመጣል። ልብ ሳለው ምካሪ ሰው ያስፈልጋል።', 'Well-meaning but foolish assistance can cause more harm than good. It is better to have wise advisors than enthusiastic but misguided helpers.'),
('the-wise-person-walks-slowly', 'ልብ ያለው ሰው ቀስ ብሎ ይሄዳል', 'The wise person walks slowly.', 'አስቦ፣ ጥንቃቄ ታጥቆ የሚሄድ ሰው ስህተት አይሠራም። መቸኮል ሁሌ ጠቃሚ አይደለም።', 'A thoughtful, careful person avoids mistakes. Haste is rarely wise — deliberate action leads to better outcomes.'),
('those-at-home-are-kept-by-their-home', 'ቤት ያለ ቤቱ ይጠብቃቸዋል', 'Those at home are kept by their home.', 'ቤተሰብ ወሳኝ ዋስትና ነው። ቤት ስለሚያለ ሰው ደህንነቱ ይጠበቃል።', 'Family and home are a person''s greatest protection and anchor. Those who have a home and family are kept safe by that bond.'),
('a-clever-person-turns-an-enemy-into-a-friend', 'ብልሃተኛ ሰው ጠላቱን ወዳጅ ያደርጋል', 'A clever person turns an enemy into a friend.', 'ብልህ ሰው ጠላቱን ለማሸነፍ ሳይሆን ለመቀየር ይጥራል። ጥበብ ግጭትን ይፈታል።', 'True cleverness lies in transforming conflict into alliance. A wise person''s greatest achievement is turning adversaries into allies.'),
('one-who-did-not-sow-cannot-expect-to-reap', 'ያልዘሩ ሰው ሊያጭድ አይፈልግም', 'One who did not sow cannot expect to reap.', 'ያልሠራ ሰው ውጤት አያሻውም። ያለ ጥረት ስኬት አይገኝም።', 'Reward follows effort. Those who have not worked, invested, or planted cannot expect to harvest the fruits of labor.'),
('two-lions-cannot-live-in-the-same-place', 'ሁለት አናብስት አንድ ቦታ አይኖሩም', 'Two lions cannot live in the same place.', 'ሁለት ኃያላን ሰዎች ወይም መሪዎች ያለ ግጭት አንድ ቦታ ሊቆዩ አይችሉም።', 'Two strong leaders or powers in the same domain will inevitably clash. Authority and dominance must have clear boundaries.'),
('a-person-cannot-work-without-eating', 'ሰው ሳይበላ ሥራ አይሠራም', 'A person cannot work without eating.', 'አካል ጤና ሳይኖር ማሠራት አይቻልም። ሰው ወሳኝ ፍላጎቶቹ ሲሟሉ ነው ሥራ የሚሠራው።', 'Basic needs must be met before one can perform well. You cannot expect productivity from someone who lacks fundamental sustenance.'),
('if-there-is-a-father-there-is-a-parent', 'አባት ካለ ወላጅ ነው፣ ወላጅ ካለ አምላክ ነው', 'If there is a father, there is a parent; if there is a parent, there is God.', 'ወላጅ የልጅ ሕይወት ምሰሶ ነው። ወላጅ ያለ ሰው ምድራዊ ጸጋ አለው።', 'Parents are divine gifts. A parent is the earthly representative of divine care — their presence is among life''s greatest blessings.'),
('knowledge-grows-when-shared', 'ዕውቀት ሲዘረጋ ሀብት ሲቀነስ', 'Knowledge grows when shared; wealth diminishes.', 'ዕውቀት ሲሰጥ ይጨምራል። ሀብት ሲሰጥ ግን ይቀንሳል። ስለዚህ ዕውቀት ከሀብት ይልቅ ዘላቂ ነው።', 'Unlike material wealth, knowledge multiplies when it is shared. Giving knowledge away makes you richer; hoarding it stagnates both giver and receiver.'),
('the-patient-person-achieves-everything', 'ትዕግስት ያለው ሰው ሁሉ ነገር ያገኛል', 'The patient person achieves everything.', 'ትዕግስት ቁልፍ በጎ ዋጋ ነው። ትዕግስተኛ ሰው ቢቸቅ አይሸሽም፣ ዓላማውን ያሳካል።', 'Patience is a supreme virtue. The person who persists with patience ultimately achieves their goals, no matter the obstacles they face.'),
('an-angry-person-would-be-better-off-absent', 'ቁጡ ሰው ጠፊ ቢሆን ይሻለዋል', 'An angry person would be better off being absent.', 'ቁጡ ሰው ሲኖር ጉዳት ያስከትላል። ቁጣ ቢያቸሩ ብዙ ስህተት ሊሸሽ ይችላል።', 'Anger is destructive. An angry person causes harm simply by being present in a situation. Emotional self-control is essential to good relationships.'),
('a-person-who-has-not-grown-is-not-considered', 'ሰው ካልሠለጠነ ዕድሜ ያለፈበት አይቆጠርም', 'A person who has not grown is not considered to have lived their years.', 'ዕድሜ ብቻ ልምድ አያደርግም። ዕድገት ወሳኝ ነው — ሰው ካልተለወጠ ዕድሜ ምን ዋጋ አለው?', 'Age alone does not bring wisdom or maturity. A life without growth, learning, or transformation is not a life fully lived.'),
('love-has-no-eyes', 'ፍቅር ዓይን የለውም', 'Love has no eyes.', 'ፍቅር ምንም ጉድለት አያይም። ሰው ወዳጁን እንዳለ ይወደዋል — ብቃቱን ሳይሆን።', 'Love is blind to faults. A loving heart sees the beloved whole, not their imperfections — this is both love''s beauty and its danger.'),
('god-is-the-guardian-of-the-poor', 'ደሃ ጠበቃ ፈጣሪ ነው', 'God is the guardian of the poor.', 'ደሃ ሰው ከሰው ሳይረዳ ቢቀር፣ ፈጣሪ ይጠብቀዋል። ፍትህ መጨረሻ ይሸነፋል።', 'The poor are not without protection — divine justice ultimately prevails. This proverb offers comfort and a reminder that human injustice is not the final word.');

-- Note: Tags and Proverb_Tags should ideally be populated dynamically or via a script,
-- but the basic proverbs are seeded above so the search function has content.
